questions =  [
    {"id": 0, "question": "Estate tax should be removed from our economic structure.", "effects": {"right": 1}},
	{"id": 1, "question": "Alternative minimum tax should be removed at the Federal level.", "effects": {"right": 1}},
	{"id": 2, "question": "The more employees an employer has working for them, the lower their personal taxes should be.", "effects": {"right": 1}},
	{"id": 3, "question": "It is not a good idea for college education to be paid for by the government as it would increase taxes.", "effects": {"right": 1}},
	{"id": 4, "question": "Trickle-down economics is a good idea.", "effects": {"right": 1}},
	{"id": 5, "question": "Those with the ability to pay should have access to higher standards of medical care.", "effects": {"right": 1}},
	{"id": 6, "question": "The rich are too highly taxed.", "effects": {"right": 1}},
	{"id": 7, "question": "Land should be a commodity to be bought and sold.", "effects": {"right": 1}},
	{"id": 8, "question": "Laissez Faire capitalism is the best economic structure.", "effects": {"right": 1}},
	{"id": 9, "question": "Freedom of business is the best practical way a society can prosper.", "effects": {"right": 1}},
    {"id": 10, "question": "Controlling inflation is more important than controlling unemployment.", "effects": {"right": -1}},
	{"id": 11, "question": "People are ultimately divided more by class than by nationality.", "effects": {"right": -1}},
	{"id": 12, "question": "The United States should consider Keynesian Economics when making and enforcing policy.", "effects": {"right": -1}},
	{"id": 13, "question": "The Federal minimum wage should be higher.", "effects": {"right": -1}},
	{"id": 14, "question": "To each according to his ability, to each according to his needs.", "effects": {"right": -1}},
	{"id": 15, "question": "Workers should seize the means of production.", "effects": {"right": -1}},
	{"id": 16, "question": "Socialism is a better alternative to Capitalism.", "effects": {"right": -1}},
	{"id": 17, "question": "Food stamps should be available for those who can’t afford food.", "effects": {"right": -1}},
	{"id": 18, "question": "Countries like the United States should help struggling countries financially. ", "effects": {"right": -1}},
	{"id": 19, "question": "The Government should provide some form of healthcare.", "effects": {"right": -1}},
    {"id": 20, "question": "Authority is okay if it’s used to push morally correct agendas.", "effects": {"auth": 1}},
	{"id": 21, "question": "Withholding/Restricting people’s freedoms is sometimes necessary to maintain peace and national security.", "effects": {"auth": 1}},
	{"id": 22, "question": "Hate Speech should be illegal and people who partake in it should be held accountable by law.", "effects": {"auth": 1}},
	{"id": 23, "question": "The police should not need a warrant to enter a house if they suspect illegal activity. ", "effects": {"auth": 1}},
	{"id": 24, "question": "Private businesses should be obligated to do business with customers even if they disagree with their beliefs.", "effects": {"auth": 1}},
	{"id": 25, "question": "If you have nothing to hide, then privacy doesn’t matter.", "effects": {"auth": 1}},
	{"id": 26, "question": "It is okay for the Government to spy on its citizens to prevent terrorist attacks.", "effects": {"auth": 1}},
	{"id": 27, "question": "The Government should limit the kind of information available to the public to prevent the spread of hatred.", "effects": {"auth": 1}},
	{"id": 28, "question": "Vaccinations should be made mandatory by the Government. ", "effects": {"auth": 1}},
	{"id": 29, "question": "In times of crisis, safety becomes more important than civil liberties.", "effects": {"auth": 1}},
    {"id": 30, "question": "Skepticism is good; people should question every decision the Government makes.", "effects": {"auth": -1}},
	{"id": 31, "question": "Security is a human problem.", "effects": {"auth": -1}},
	{"id": 32, "question": "A driver’s license should not be required to operate a motor vehicle on public roads.", "effects": {"auth": -1}},
	{"id": 33, "question": "Someone who served their sentence after committing a crime should have their rights fully reinstated.", "effects": {"auth": -1}},
	{"id": 34, "question": "Crypto currency should not be regulated by any government.", "effects": {"auth": -1}},
	{"id": 35, "question": "A law abiding citizen should be able to own a firearm.", "effects": {"auth": -1}},
	{"id": 36, "question": "The Government shouldn’t recognize marriage.", "effects": {"auth": -1}},
	{"id": 37, "question": "The constitution should not, under any circumstance, be changed or altered. ", "effects": {"auth": -1}},
	{"id": 38, "question": "The smaller the government, the freer the people. ", "effects": {"auth": -1}},
	{"id": 39, "question": "State schools are a bad idea because our state shouldn't be influencing our children. ", "effects": {"auth": -1}},
    {"id": 40, "question": "Employers should pay for their employee’s daycare/babysitters for workdays.", "effects": {"prog": 1}},
	{"id": 41, "question": "Mental health should be taken seriously by employers.", "effects": {"prog": 1}},
	{"id": 42, "question": "Schools should not make classroom attendance compulsory.", "effects": {"prog": 1}},
	{"id": 43, "question": "No one chooses their country of birth, so it’s foolish to be proud of it.", "effects": {"prog": 1}},
	{"id": 44, "question": "Gendered sports leagues should be based off of biological sex.", "effects": {"prog": 1}},
	{"id": 45, "question": "Consumption of drugs should be entirely decriminalized.", "effects": {"prog": 1}},
	{"id": 46, "question": "Adults should have the freedom to body autonomy.", "effects": {"prog": 1}},
	{"id": 47, "question": "The death penalty, under no circumstance, should be exercised.", "effects": {"prog": 1}},
	{"id": 48, "question": "Non-offending pedophiles should be allowed in society.", "effects": {"prog": 1}},
	{"id": 49, "question": "Homosexuality should be accepted and is okay.", "effects": {"prog": 1}},
    {"id": 50, "question": "Good parents sometimes have to spank their children.", "effects": {"prog": -1}},
	{"id": 51, "question": "Abortion, when the woman’s life is not threatened, should always be illegal.", "effects": {"prog": -1}},
	{"id": 52, "question": "I’d always support my country, whether it was right or wrong.", "effects": {"prog": -1}},
	{"id": 53, "question": "America is a historically Christian country so Christian values should be taught in schools.", "effects": {"prog": -1}},
	{"id": 54, "question": "Marriage should only be between a man and a woman.", "effects": {"prog": -1}},
	{"id": 55, "question": "Children, under no circumstance, should be allowed to go through hormonal therapy with the intention of transitioning.", "effects": {"prog": -1}},
	{"id": 56, "question": "People with serious inheritable disabilities should not be allowed to reproduce.", "effects": {"prog": -1}},
	{"id": 57, "question": "Pornography should be banned.", "effects": {"prog": -1}},
	{"id": 58, "question": "People shouldn’t date outside their own race.", "effects": {"prog": -1}},
	{"id": 59, "question": "Multiculturalism is bad.", "effects": {"prog": -1}},
];
